"""Policy Recommendation model for security policy suggestions."""

from __future__ import annotations

from datetime import datetime
from typing import List, Optional
from pydantic import BaseModel, Field


class PolicyRecommendation(BaseModel):
    """Security policy recommendation generated by the system."""

    # Metadata
    recommendation_id: str = Field(..., description="Unique identifier for the recommendation")
    timestamp: datetime = Field(..., description="Timestamp when recommendation was generated")
    source: str = Field(..., description="Source of the recommendation (engine, user, etc.)")

    # Recommendation details
    recommended_action: str = Field(..., description="Recommended action")
    reason: str = Field(..., description="Reason for the recommendation")
    confidence: float = Field(..., description="Confidence in the recommendation (0.0-1.0)")
    
    # Target information
    target_flow_id: Optional[str] = Field(None, description="Flow this recommendation relates to")
    target_host: Optional[str] = Field(None, description="Host this recommendation relates to")
    
    # Additional metadata
    references: List[str] = Field(default_factory=list, description="References or sources")

    class Config:
        """Pydantic configuration."""
        use_enum_values = True
        validate_assignment = True